### ISSUE TITLE
Partie Euro2016 sans connexion ?

### ISSUE THREAD

**Issue by wilsto** [wilsto/EuroProno2016_Web#20]
La partie matchs et équipes pour l'euro 2016 ne sont accessible qu'après identification, peut on la laisser libre d'accès ?

**Comment by CedDev** [comment]
dans le fichier ts dans
 stateprovider, ajout authenticate: true
 ou le groupe d'authentification authenticate: 'admin' 
ou rien si pas libre d'accès
