### ISSUE TITLE
Order Team ne fonctionne pas

### ISSUE THREAD

**Issue by wilsto** [wilsto/EuroProno2016_Web#36]

**Comment by CedDev** [comment]
avec l'ajout de translate, cela ne fonctionne plus

**Comment by CedDev** [comment]
reprise du code pour remettre {{'sort by name' | translate}}

**Comment by wilsto** [comment]
non c'est bon j'ai corrigé

**Comment by wilsto** [comment]
c'est pour çà que je l'ai mis dans closed
