### ISSUE TITLE
Ligue Création

### ISSUE THREAD

**Issue by wilsto** [wilsto/EuroProno2016_Web#8]

**Comment by CedDev** [comment]
créer une ligue
publique ou privée
si privée nécessite acceptation de l'owner

rejoindre une ligue
avec envoi de mail à l'owner à chaque inscription

"ligues des champions" privée et payante

**Comment by CedDev** [comment]
prorpiétés de ligue : nom, privé/publique, gratuit/avec mise, description, { liste des joueurs avec statut validé ou non }
