### ISSUE TITLE
Unable to Save Prono

### ISSUE THREAD

**Issue by plample** [wilsto/EuroProno2016_Web#97]
In /prono, it is impossible to save the scores proposed on IE11 and Chrome. Worked in Safari.

**Comment by wilsto** [comment]
Correction : vérification du chargement complet du playerId avant de lancer la commande loadprono

**Comment by wilsto** [comment]
@plample, si ok, tu peux cloturer

**Comment by plample** [comment]
Merci, ça fonctionne.
Bravo boss
